[general]
OPENAI_API_KEY = "proj-n5L2RUwJMh-oXdgLQSS7oSP3Omnv2J1XP8G6c7NCrkyca6qf3nw7QWCO4nuiE-9kb8Gqm45q2QT3BlbkFJF6acnYqNHEqt5EtrCCchfG0zzEldVrT8TAxgh2WNdOgWM_Jwn5KlOGN5fCnvU8FZFf_Fl-z74A"
GEOCODER_USER_AGENT = "talentscout-app"